### ISSUE TITLE
Difficulty Building/Running

### ISSUE THREAD

**Issue by sparxooo** [IMS-MAXIMS/openMAXIMS#29]
Hi all.

Tried building openMAXIMS on a Windows Server 2008 R2 VM, with SQL Server 2012.

I followed the steps stated in the instructions, to fall at a few hurdles, get up over them, and then fell at some more.

JDK 1.5 as supplied will not compile the project, as some lib files are version 50.0, not 49.0.

Upgrading JDK to 1.6 will then compile the project (changing the camel case problem listed elsewhere).

When attempting to run the project, I cannot get it to run past a "500 error". The logs from Tomcat seem to indicate an error with the SQL implementation, but i'm not really sure.

Can we get an idea of what versions of tools we definitely need to compile this source code now?

Regards,

**Comment by ThiyagarajanJayaraman** [comment]
Hi

You should be able to compile openMAXIMS with JDK 1.7. Regarding the error with the database, it might be due to the database connection configuration that you are getting this error. Could you try configuring the database using a context specified in server configuration as below. Please, change the folder paths and the database configuration as per your local configuration and let us know if you need any futher information.

Context to be set in Server.xml

                        <Context path="/openMAXIMS" reloadable="false" docBase="openMAXIMS">

                                    <Environment name="OpenOfficeHomePath"   type="java.lang.String" value="C:\IMS\OpenOffice.org 3"/>
                                    <Environment name="QuartzDbDriver" type="java.lang.String" value="com.microsoft.sqlserver.jdbc.SQLServerDriver" />
                                    <Environment name="QuartzDbUrl" type="java.lang.String" value="jdbc:sqlserver://localhost:1433;databaseName=LOCALDBNAME" />
                                    <Environment name="QuartzDbUsername" type="java.lang.String" value="USERNAME" />
                                    <Environment name="QuartzDbPassword" type="java.lang.String" value="PASSWORD" />

                                    <Resource name="jdbc/maxims_uat"
                                                type="com.mchange.v2.c3p0.ComboPooledDataSource"
                                                auth="Container"
                                                driverClass="com.microsoft.sqlserver.jdbc.SQLServerDriver"
                                                jdbcUrl="jdbc:sqlserver://localhost:1433;databaseName=LOCALDBNAME"
                                                user="USERNAME"
                                                password="PASSWORD"
                                                factory="org.apache.naming.factory.BeanFactory"

                                                minPoolSize="5"
                                                maxPoolSize="100"
                                                maxIdleTime="300"
                                                testConnectionOnCheckin="true"
                                                idleConnectionTestPeriod="30"
                                                checkoutTimeout="5000"
                                                unreturnedConnectionTimeout="3600"
                                                debugUnreturnedConnectionStackTraces="true"
                                                preferredTestQuery="select top 1 * from appdbversion" />
                        </Context>



Thiyagarajan Jayaraman
Software Engineer

**Comment by testedtechs** [comment]
I'm a noob in Java and really want to expand my knowledge.....

I've buiilt the war file but still having 500 error....

I have a local instalation of mssql and apache but cant get the app to run.

I can only find web.xml and WebAppBuild.xml... no server.xml file....

Please...what I'm I missing or still need to do.

Regards

**Comment by sparxooo** [comment]
Hi Thiyagarajan thanks for the reply.

Windows Server 2003 Eval, MSSQL 2008, Tomcat 5.5.9, JDK 7. I have compiled  a clean copy of the source this time round, changing the necessary files to camel case.

I also had to edit the "server-config.wsdd" file to add a space to the "<?xml version="1.0" encoding="UTF-8" ?>" line (between the final quotes and question mark) as Tomcat was complaining about a faulty Xml file.

The database connection issue now seems to have been fixed with your updated configuration, Unfortunately I now appear to have quite a difficult issue to fix.

Server log "maxims" - http://pastebin.ca/3775251

The Tomcat server just freezes entirely. If I remove the JDBC library then the server stays responsive but errors show about not being able to connect to the db.

**Comment by ThiyagarajanJayaraman** [comment]
Hi

Could you try Tomcat 7 instead of 5.5.9, please?

Thanks

Thiyagarajan Jayaraman
Software Engineer

**Comment by sparxooo** [comment]
Hi,

I have tried both Tomcat 7 and 5.5.9 with the same result (no web response and hanging Tomcat - not even the management interface will respond).

I am wondering if the libraries are going to cause an issue (compiling against Tomcat 7 libraries causes an issue with the dbcp dependency) with running on later Tomcat versions.

Does IMS use an IDE internally to develop maxims and maintain libraries/dependencies/debugging or is it all done through the build file? 

Regards,

**Comment by pacharanero** [comment]
Internally IMS uses its own IDE ('IMS-IDE') to develop opemMAXIMS. As of the last time I discussed it with them, this IMS-IDE was not open source, although they have agreed to make it available to the NHS (NHS = our National Health Service for anyone outside of UK).

I'm not sure how this works if you are an independent developer trying out openMAXIMS, as I am. Given the fact that nobody has managed to get a running instance of openMAXIMS working outside of IMS, I'm concerned about how open source this project really is. We the community clearly haven't been given access to everything that is needed to build openMAXIMS.

**Comment by sparxooo** [comment]
Hi pacharanero,

Let's not tar IMS with the same brush I would tar some other open source projects and managing companies with (*cough* router/stb manufacturers *cough*) - they've done the big step of making the large majority of their source public, with the possible downsides that may bring. Not only that but there is at least one person (if i'm not mistaken  Thiyagarajan), that is supporting this open source project from IMS.

I'm willing to wait and see entirely what the future brings and in the mean time I will fiddle and faff with it (including trying to get it into an IDE Netbeans/Eclipse) and getting it to run. MSSQL is not my DB of choice, so any advice on getting MySQL supported or specified even better. 

Here's to open source! 👍

**Comment by ThiyagarajanJayaraman** [comment]
Hi

Could you let me know if you have run the MAXIMS_RefDataMSQ05.sql under openMAXIMS/Source Library/openmaxims_workspace/WebApp/, which adds reference data, please? If you haven’t done already, please run it so that you will have all the reference data and this will help start the application.

Thanks

Thiyagarajan Jayaraman
Software Engineer

**Comment by sparxooo** [comment]
Hi TJ,

Yes I have added all the data to the database.

I have also tried exporting the schema using the build file also.

Regards,

**Comment by sparxooo** [comment]
As a further update to the IDE subject - I have got the whole project to compile inside NetBeans successfully with it automatically building the war file also - same result as running the previous build - next step to enable debugging and try to locate where it is getting stuck on the web requests.

Have IMS added anything to the codebase internally that they can update (or push a full update to Github) of a definitely working codebase and associated schema/reference data?

I understand that IMS may not use git internally but having regular updates could help this project on its way, as well as having the ability for third party input on security or functionality bugs.

Regards,

**Comment by sparxooo** [comment]
Maybe a breakthrough (or not).

After compiling the project again through NetBeans I tried to run it on my own machine (not in a VM, using the SQL server through a virtual network connection). I forgot, however, to ensure that the SQL Server had started correctly (the service had been set to Manual start).

Instead of the infinite loading web request, I got this in my logs: http://pastebin.com/Lh6jtzUw
Tomcat was also responsive and I could load the manager apps. The maxims interface would also bring up the "500 error" again.

I started the SQL server (and added another database driver resource line in the context file, for MyDS), and restarted Tomcat - back to infinite requests and no content. It now appears that it has made this "permanent" - stopping the sql server now just brings up the infinite requests and no more "deadlock" errors.

**Comment by sparxooo** [comment]
Further information.

Debugging line by line, and activating the "all" level of logging, I appear to have found one of the issues.

The code wants to find a "Default" ConfigFlagsGroup, however there is not a ConfigFlagsGroup in the database. The code then tries to create one, by creating a new ConfigFlagsGroup class, and saving it  - this however seems to fail for some reason, and the code then once again tries to get the "Default" ConfigFlagsGroup from the database, and that query then hangs the application.

Adding a row to the table dbo.core_configflaggrou with Name = "Default" and Version = 0 allows the application to continue its loading - and I got presented with a Login screen.

I still get a 500 error on attempting to login, but at least we have something now!

**Comment by sparxooo** [comment]
Eventually got it working, although there are still issues. This project is quite broken.

Steps to get running:
1) Download full copy of this repo
2) Rename the "EmergencyEpisodeLite*" files under ValueObjects/ from lower case to CamelCase.
3) Edit the server-config.wsdd and add a space before the last ?> after the comment
4) Run ant -w WebAppBuild.xml SchemaExport
5) Create the database, and use schema_export.sql (DomainObjects/) to create the database structure
6) Edit the MAXIMS_RefDataMSQ05.sql file, for the last query - change CONVERT("date", date()) to DATE()
`-- Insert openmaxims to configflaggrou table.
insert into core_configflaggrou (class, vstp, rie, sys_creation_datetime, sys_lastupdate_datetime, sys_creation_user, sys_lastupdate_user, name)
values (null,0,null,CONVERT(date, getdate()),null,'openmaxims',null,'Default')
go
`
7) Edit this file for the username / password - Run this file to populate the database objects.
8) Compile the project as before
9) Add a context file for this project, containing this:`<Context path="/openmaxims" reloadable="false" docBase="E:/Build/openMAXIMS" processTlds="false" >
<Environment name="OpenOfficeHomePath"   type="java.lang.String" value="C:\OpenOffice.org3"/>
<Environment name="QuartzDbDriver" type="java.lang.String" value="com.microsoft.sqlserver.jdbc.SQLServerDriver" />
<Environment name="QuartzDbUrl" type="java.lang.String" value="jdbc:sqlserver://10.0.0.252:1433;databaseName=openmaxims" />
<Environment name="QuartzDbUsername" type="java.lang.String" value="openmaxims" />
<Environment name="QuartzDbPassword" type="java.lang.String" value="password" />
<Resource name="jdbc/mydb"
                                                type="com.mchange.v2.c3p0.ComboPooledDataSource"
                                                auth="Container"
												driverClass="com.microsoft.sqlserver.jdbc.SQLServerDriver"
                                                jdbcUrl="jdbc:sqlserver://10.0.0.252:1433;databaseName=openmaxims"
                                                user="openmaxims"
                                                password="password"
                                                factory="org.apache.naming.factory.BeanFactory"

                                                minPoolSize="10"
                                                maxPoolSize="100"
                                                maxIdleTime="300"
                                                testConnectionOnCheckin="true"
                                                idleConnectionTestPeriod="30"
                                                checkoutTimeout="5000"
                                                unreturnedConnectionTimeout="3600"
                                                debugUnreturnedConnectionStackTraces="true"
                                                preferredTestQuery="select top 1 * from appdbversion" />

						<Resource name="jdbc/myDS"
                                                type="com.mchange.v2.c3p0.ComboPooledDataSource"
                                                auth="Container"
												driverClass="com.microsoft.sqlserver.jdbc.SQLServerDriver"
                                                jdbcUrl="jdbc:sqlserver://10.0.0.252:1433;databaseName=openmaxims"
                                                user="openmaxims"
                                                password="password"
                                                factory="org.apache.naming.factory.BeanFactory"

                                                minPoolSize="10"
                                                maxPoolSize="100"
                                                maxIdleTime="300"
                                                testConnectionOnCheckin="true"
                                                idleConnectionTestPeriod="30"
                                                checkoutTimeout="5000"
                                                unreturnedConnectionTimeout="3600"
                                                debugUnreturnedConnectionStackTraces="true"
                                                preferredTestQuery="select top 1 * from appdbversion" />
                        </Context>
`
Change the database address, username, password, and docbase where appropriate.
10) Add this to catalina.properties (Tomcat conf): `javax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
javax.xml.transform.TransformerFactory=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl
javax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl
javax.xml.datatype.DatatypeFactory=com.sun.org.apache.xerces.internal.jaxp.datatype.DatatypeFactoryImpl`

11) Start Tomcat, and this should hopefully run.

I have run openMAXIMS on this config:
Windows 10
Java 7 SDK
MSSQL 2005 (I used the Express Edition, with TCP connection turned on)
Tomcat 9

The only issue is that when you create your user, i am not certain whether you need to encrypt the password you put in c_password - i had to use the debugger to select the user without specifying the password as it would not initially accept the password i had put in, but once changed inside maxims, it accepted it as normal.

I have managed to get it running and users created, etc. Some forms don't appear, and I still get errors regarding "careuk" AccessLogic - I think this is because of the previous non-complete renaming of the CareUK stuff.

A very large project, it does take time to get going, but I have had a bit of an adventure getting it running!
